name: Windows x86_64 Build Reusable Workflows
on: 
  workflow_call:
    outputs:
      tag_name:
        description: "Generated tag"
        value: ${{ jobs.build-mingw.outputs.tag_name }}
      release_name:
        description: "Generated release name"
        value: ${{ jobs.build-mingw.outputs.release_name }}
  workflow_dispatch:

jobs:
  build-mingw:
    uses: ./.github/workflows/win-mingw.yml

  build-msvc:
    needs: build-mingw
    uses: ./.github/workflows/win-msvc.yml
